Update config files and README examples
membraneframework/membrane_portaudio_plugin pull request #31
Opened 2023-02-09 15:28 UTC by Janix4000

2023-02-10 16:09 UTC, varsill requested changes

2023-02-10 16:09 UTC, varsill commented on .editorconfig
> +root = true
do we want this? :D

2023-02-13 10:22 UTC, Janix4000 commented on .editorconfig
> +root = true
Ask author of this line https://github.com/membraneframework/membrane_template_plugin/blob/903c4580ebb33dc4165bdc33d149c59aa1e60a6f/.editorconfig#L1

2023-02-13 10:23 UTC, Janix4000 commented on .editorconfig
> +root = true
¯\_(ツ)_/¯

2023-02-13 10:57 UTC, varsill approved these changes

2023-02-15 10:34 UTC, merged