725 portaudio rename endpoint_id to device_id
membraneframework/membrane_portaudio_plugin pull request #54
Opened 2024-03-07 10:14 UTC by kidq330

2024-03-08 08:23 UTC, varsill commented on README.md
> +	{:membrane_portaudio_plugin, "~> 0.18.5"}
since this one changes API, we need to release v0.19.0

2024-03-11 09:45 UTC, mat-hek requested changes

2024-03-11 09:45 UTC, mat-hek commented on lib/membrane_portaudio_plugin/source.ex
> +  def_options device_id: [
I'd leave the old option, but document it as deprecated and warn in `handle_init`

2024-03-11 14:34 UTC, mat-hek commented on lib/membrane_portaudio_plugin/source.ex
> +    _warning = Membrane.Logger.warning("endpoint_id has been renamed to device_id")
```suggestion
    Membrane.Logger.warning("endpoint_id option has been renamed to device_id")
```

2024-03-13 11:34 UTC, mat-hek approved these changes

2024-03-14 15:12 UTC, merged